from enum import IntEnum


class HEATING_TYPE(IntEnum):
    SOLAR_PISCINA = 0
    TROCADOR_CALOR_PISCINA = 1
    ELETRICO_PISCINA = 2
    SOLAR_RESIDENCIAL = 3
    APOIO_GAS = 4
    APOIO_ELETRICO = 5
    RECIRCULACAO_BARRILETE = 6
    TROCADOR_CALOR_FAIRLAND = 7
    AQUECIMENTO = 8
    REFRIGERACAO = 9
    TERMOSTATO = 10


class HEATING_OP_MODE(IntEnum):
    DESLIGADO = 0
    LIGADO = 1
    AUTOMATICO = 2
    ECONOMICO = 3
    AQUECER = 4
    RESFRIAR = 5
