from enum import IntEnum

class MONITOR_TYPE(IntEnum):
    CLORADOR = 0
    CLORADOR_TURBO = 1

class MONITOR_OP_MODE(IntEnum):
    DESLIGADO = 0
    LIGADO = 1
    AUTOMATICO = 2

class MONITOR_STATUS(IntEnum):
    SEM_SAL = 0
    SAL_BAIXO = 1
    SAL_OK = 2
    SAL_ALTO = 3
    SAL_CRITICO = 4

CHLORINATOR_TYPES = (MONITOR_TYPE.CLORADOR, MONITOR_TYPE.CLORADOR_TURBO)

MONITOR_STATUS_NAMES = {
    MONITOR_STATUS.SEM_SAL: "Sem sal",
    MONITOR_STATUS.SAL_BAIXO: "Sal baixo",
    MONITOR_STATUS.SAL_OK: "Sal ok",
    MONITOR_STATUS.SAL_ALTO: "Sal alto",
    MONITOR_STATUS.SAL_CRITICO: "Nível crítico de sal",
}

MONITOR_OP_MODE_NAMES = {
    MONITOR_OP_MODE.DESLIGADO: "Desligado",
    MONITOR_OP_MODE.LIGADO: "Ligado",
    MONITOR_OP_MODE.AUTOMATICO: "Automático",
}
